default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: nats_development

test:
  <<: *default
  database: nats_test

production:
  <<: *default
  database: nats_production
